# Версия docker-compose
version: "3.8"

# Список наших сервисов (контейнеров)
services:
    nginx:
      # используем последний стабильный образ nginx
        # image: nginx:latest
        build:
            context: .
            dockerfile: ./images/nginx/Dockerfile
        container_name: "nginx"
        # маршрутизируем порты
        ports:
            - "8000:80"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./logs:/var/log/nginx
            # - ./domains:/var/www
            - ./domains/docker.test:/var/www/docker.test
            - ./domains/hello.test:/var/www/hello.test

            - ./domains/symfony.test/bin:/var/www/symfony.test/bin
            - ./domains/symfony.test/config:/var/www/symfony.test/config
            - ./domains/symfony.test/migrations:/var/www/symfony.test/migrations
            - ./domains/symfony.test/public:/var/www/symfony.test/public
            - ./domains/symfony.test/src:/var/www/symfony.test/src
            - ./domains/symfony.test/templates:/var/www/symfony.test/templates
            - ./domains/symfony.test/var:/var/www/symfony.test/var

            - ./domains/yii.test:/var/www/yii.test
        # nginx должен общаться с php контейнером
        depends_on:
            - php
    php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build:
            context: .
            dockerfile: ./images/php/Dockerfile
        container_name: "php"
        # монтируем директорию с проектами
        volumes:
            # - ./domains:/var/www
            - ./domains/docker.test:/var/www/docker.test
            - ./domains/hello.test:/var/www/hello.test

            - ./domains/symfony.test/bin:/var/www/symfony.test/bin
            - ./domains/symfony.test/config:/var/www/symfony.test/config
            - ./domains/symfony.test/migrations:/var/www/symfony.test/migrations
            - ./domains/symfony.test/public:/var/www/symfony.test/public
            - ./domains/symfony.test/src:/var/www/symfony.test/src
            - ./domains/symfony.test/templates:/var/www/symfony.test/templates
            - ./domains/symfony.test/var:/var/www/symfony.test/var

            - ./domains/yii.test:/var/www/yii.test
        # этот образ будет общаться с mysql
        depends_on:
            - mysql
    pma:
        image: phpmyadmin/phpmyadmin
        container_name: "phpmyadmin"
        ports:
            - 8183:80
        environment:
            PMA_HOST: mysql
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: secret
        restart: always
        depends_on:
            - mysql
    mysql:
        image: mysql
        container_name: "mysql"
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        # задаем пароль для root пользователя
        environment:
            MYSQL_ROOT_PASSWORD: secret
        restart: always
