FROM nginx:latest

COPY ["domains/docker.test", "/var/www/docker.test"]
COPY ["domains/hello.test", "/var/www/hello.test"]
COPY ["domains/symfony.test", "/var/www/symfony.test"]
COPY ["domains/yii.test", "/var/www/yii.test"]